#!/usr/bin/env python

from werkzeug.wsgi import SharedDataMiddleware
from werkzeug.exceptions import NotFound
from werkzeug.serving import run_simple

app = SharedDataMiddleware(NotFound(), {
    '/': '_site/',
}, cache_timeout=0)

run_simple('127.0.0.1', 8000, app)
